include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    prefer_relative_imports: true
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
