name: bax
description: Search for speed.

publish_to: "none"

version: 1.0.2+16

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.2.3
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_auth_mocks: ^0.9.2
  speed_test_dart: ^1.0.4+1
  network_info_plus: ^3.0.1
  permission_handler: ^10.2.0
  freezed_annotation:
  json_annotation: ^4.7.0
  cloud_firestore: ^4.3.1
  flutter_svg: ^1.1.6
  http: ^0.13.5
  flutter_inappwebview: ^5.7.2+3
  location: ^4.4.0
  geolocator: ^9.0.2
  share_plus: ^6.3.0
  roggle: ^0.3.0
  intl: ^0.17.0
  firebase_dynamic_links: ^5.0.11
  shared_preferences: ^2.0.17
  package_info_plus: ^3.0.3
  url_launcher: ^6.1.9
  geoflutterfire_plus: ^0.0.3
  purchases_flutter: ^4.10.4
  flutter_riverpod: ^2.3.1
  collection: ^1.17.0
  go_router: ^6.5.1
  firebase_analytics: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_lint: ^1.1.3

  flutter_lints: ^2.0.0
  freezed:
  build_runner:
  json_serializable: ^6.5.4
  pedantic_mono:
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Thin.otf
        - asset: fonts/NotoSansJP-Light.otf
        - asset: fonts/NotoSansJP-Regular.otf
        - asset: fonts/NotoSansJP-Medium.otf
        - asset: fonts/NotoSansJP-Bold.otf
        - asset: fonts/NotoSansJP-Black.otf

  assets:
    - assets/map_style_silver.json
    - assets/images/
    - assets/launcher_icon/
