name: bax
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^6.0.1
  google_maps_flutter: ^2.2.3
  firebase_core: ^2.4.1
  flutter_riverpod: ^2.1.3
  firebase_auth: ^4.2.5
  firebase_auth_mocks: ^0.9.2
  speed_test_dart: ^1.0.4+1
  network_info_plus: ^3.0.1
  permission_handler: ^10.2.0
  freezed_annotation:
  json_annotation: ^4.7.0
  cloud_firestore: ^4.3.1
  http: ^0.13.5
  flutter_inappwebview: ^5.7.2+3
  location: ^4.4.0
  geoflutterfire_plus:
    git:
      url: https://github.com/KosukeSaigusa/geoflutterfire_plus

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed:
  build_runner:
  json_serializable: ^6.5.4
  pedantic_mono:
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Thin.otf
        - asset: fonts/NotoSansJP-Light.otf
        - asset: fonts/NotoSansJP-Regular.otf
        - asset: fonts/NotoSansJP-Medium.otf
        - asset: fonts/NotoSansJP-Bold.otf
        - asset: fonts/NotoSansJP-Black.otf
